- name: Install kmod-nft-bridge
  opkg:
    update_cache: true
    name: kmod-nft-bridge
    state: installed

- name: Install nftables rules
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
  notify: reload nftables

- name: Load nftables rules on boot
  lineinfile:
    path: /etc/rc.local
    line: 'nft -f /etc/nftables.conf || true'
    insertbefore: '^exit 0$'

- name: Set isolate flag on wireless interfaces
  uci:
    command: set
    key: '{{ item }}'
    value:
      isolate: 1
  loop:
  - wireless.default_radio0
  - wireless.default_radio1

- name: Commit UCI transaction
  uci:
    command: commit
  notify: reload wifi
