openwrt:
  vars:
    openwrt_install_recommended_packages: false
  hosts:
    c7-toilettencontainer:
      ansible_host: 10.100.13.169
    c7-elektrikercontainer:
      ansible_host: 10.100.13.170
    c7-studioillegale:
      ansible_host: 10.100.13.171
    c7-bretter:
      ansible_host: 10.100.13.172
    acmesh-radiobremen-links:
      ansible_host: 10.100.13.198
    acmesh-elektrikercontainer:
      ansible_host: 10.100.13.199
    acmesh-vip-flut:
      ansible_host: 10.100.13.200
    c7-flut-vip:
      ansible_host: 10.100.13.201
    acmesh-studioillegale:
      ansible_host: 10.100.13.202
    acmesh-schleuse-gastro:
      ansible_host: 10.100.13.213
    c7-schleuse-gastro:
      ansible_host: 10.100.13.214
    c7-bauwagen:
      ansible_host: 10.100.13.218
    acmesh-schleuse-backstage-1:
      ansible_host: 10.100.13.220
    acmesh-schleuse-backstage-2:
      ansible_host: 10.100.13.186
    c7-schleuse-backstage-1:
      ansible_host: 10.100.13.222
    c7-schleuse-backstage-2:
      ansible_host: 10.100.13.184
    c7-radiobremen:
      ansible_host: 10.100.13.223
    acmesh-buerocontainer:
      ansible_host: 10.100.13.225
    acmesh-dritter-baum-richtung-flut:
      ansible_host: 10.100.13.227
    acmesh-muchasmas:
      ansible_host: 10.100.13.190
    c7-muchasmas:
      ansible_host: 10.100.13.189
    c7-kunsttunnel:
      ansible_host: 10.100.13.197
    c7-lwlcom:
      ansible_host: 10.100.13.206
    acmesh-lwlcom-1:
      ansible_host: 10.100.13.187
    acmesh-lwlcom-2:
      ansible_host: 10.100.13.188
    acmesh-radiobremen-buehne:
      ansible_host: 10.100.13.192
    c7-radiobremen-buehne:
      ansible_host: 10.100.13.193
    c7-pappinale-container:
      ansible_host: 10.100.13.181
    acmesh-pappinale-container:
      ansible_host: 10.100.13.182
    c7-pappinale-backstage:
      ansible_host: 10.100.13.180
    acmesh-pappinale-backstage-1:
      ansible_host: 10.100.13.179
    acmesh-pappinale-backstage-2:
      ansible_host: 10.100.13.178
    c7-auf-dem-bauwagen:
      ansible_host: 10.100.13.176
    c7-irgendwo-flut:
      ansible_host: 10.100.13.185
    acmesh-irgendwo-flut:
      ansible_host: 10.100.13.196
    # sehr langsam
    #acmesh-kunsttunnel-laterne:
    #  ansible_host: 10.100.13.194
