openwrt:
  vars:
    openwrt_install_recommended_packages: false
  hosts:
    acmesh-radiobremen-links:
      ansible_host: 10.100.13.198
    acmesh-elektrikercontainer:
      ansible_host: 10.100.13.199
    acmesh-vip-flut:
      ansible_host: 10.100.13.200
    c7-flut-vip:
      ansible_host: 10.100.13.201
    c7-studioillegale:
      ansible_host: 10.100.13.204
    c7-elektrikercontainer:
      ansible_host: 10.100.13.205
    c7-bretter:
      ansible_host: 10.100.13.208
    acmesh-schleuse-gastro:
      ansible_host: 10.100.13.213
    c7-schleuse-gastro:
      ansible_host: 10.100.13.214
    c7-bauwagen:
      ansible_host: 10.100.13.218
    acmesh-schleuse-backstage:
      ansible_host: 10.100.13.220
    c7-schleuse-backstage:
      ansible_host: 10.100.13.222
    c7-radiobremen-1:
      ansible_host: 10.100.13.223
    acmesh-buerocontainer:
      ansible_host: 10.100.13.225
    acmesh-dritter-baum-richtung-flut:
      ansible_host: 10.100.13.227
    acmesh-muchasmas:
      ansible_host: 10.100.13.190
    c7-kunsttunnel:
      ansible_host: 10.100.13.197
    c7-lwlcom:
      ansible_host: 10.100.13.206
    acmesh-lwlcom-1:
      ansible_host: 10.100.13.187
    acmesh-lwlcom-2:
      ansible_host: 10.100.13.188
