# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 2s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    org: "ffhb"

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: "https"
    static_configs:
    - targets:
      - "alerts.sum7.eu"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - '/opt/alerts/*.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'icmp-backbone'
    metrics_path: /probe
    scrape_interval: 2s
    params:
      module: [icmp]
    file_sd_configs:
      - refresh_interval: 10s
        files:
          - "/opt/scrape/device_*.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: 'icmp-yanic'
    metrics_path: /probe
    scrape_interval: 2s
    params:
      module: [icmp]
    file_sd_configs:
      - refresh_interval: 10s
        files:
          - "/opt/tmp/yanic-prometheus-sd.json"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
      - source_labels: [owner]
        target_label: group

  - job_name: 'yanic'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
     - targets:
        - "127.0.0.1:8080"

#  - job_name: "snmp-airmax"
#    metrics_path: /snmp
#    scrape_interval: 5m
#    params:
#      module: [ubiquiti_airmax]
#    file_sd_configs:
#      - refresh_interval: 10s
#        files:
#          - "/opt/scrape/device_unifi.yml"
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: localhost:9116

#  - job_name: "snmp-mikrotik"
#    metrics_path: /snmp
#    scrape_interval: 5m
#    params:
#      module: [mikrotik]
#    file_sd_configs:
#      - refresh_interval: 10s
#        files:
#          - "/opt/scrape/device_mikrotik.yml"
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: localhost:9116

  - job_name: 'mikrotik'
    scrape_interval: 5m
    static_configs:
      - targets: ['localhost:9436']
