# restart respondd if not running
---
- name: check
  raw: "pgrep respondd"
  register: pgrep
  ignore_errors: yes
  changed_when: false

- name: restart
  raw: /etc/init.d/gluon-respondd restart
  when: pgrep.rc != 0
